name: cd-build-and-publish

on:
  workflow_run:
    workflows: [ci-build-and-test, release]
    types:
      - completed
  release:
    types:
      - released
  push:
    tags:
      - '*.*.*.'

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update version number in the files
        run: |
          sed -i "s/version = .*/version = '${{ github.event.release.tag_name }}'/" pyproject.toml
          sed -i "s/__version__ = .*/__version__ = '${{ github.event.release.tag_name }}'/"  ./src/mediacatch_s2t/__init__.py

      - name: Commit and push changes
        run: |
          git config user.name "gha-release"
          git config user.email "support@mediacatch.io"
          git add pyproject.toml src/mediacatch_s2t/__init__.py
          git commit -m "bump version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main

  build-and-publish:
    name: Build and publish Python distribution package to PyPI
    needs: update-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m 
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
