name: cd-build-and-publish

on:
  workflow_run:
    workflows: [ci-build-and-test, release]
    types:
      - completed
  release:
    types:
      - released
  push:
    tags:
      - '*.*.*.'

jobs:
  build-and-publish:
    name: Build and publish Python distribution package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m 
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
